/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppendVideoDialog: typeof import('./src/components/AppendVideoDialog.vue')['default']
    BiliSetting: typeof import('./src/components/BiliSetting.vue')['default']
    ButtonGroup: typeof import('./src/components/ButtonGroup.vue')['default']
    ChangelogModal: typeof import('./src/components/ChangelogModal.vue')['default']
    DanmuFactorySetting: typeof import('./src/components/DanmuFactorySetting.vue')['default']
    DanmuFactorySettingDailog: typeof import('./src/components/DanmuFactorySettingDailog.vue')['default']
    DownloadConfirm: typeof import('./src/components/DownloadConfirm.vue')['default']
    EditableText: typeof import('./src/components/EditableText.vue')['default']
    FileArea: typeof import('./src/components/FileArea.vue')['default']
    ImageCrop: typeof import('./src/components/ImageCrop.vue')['default']
    Index: typeof import('./src/components/Artplayer/Index.vue')['default']
    LogModal: typeof import('./src/components/logModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tip: typeof import('./src/components/Tip.vue')['default']
  }
}
