name: Docs Build Verification

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "npm"
          cache-dependency-path: "docs/package-lock.json"

      - name: Install dependencies
        working-directory: ./docs
        run: npm ci

      - name: Build docs
        working-directory: ./docs
        run: npm run docs:build

      # - name: Upload build artifacts
      #   if: success()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: docs-build
      #     path: docs/.vitepress/dist
      #     retention-days: 7

      # - name: Build summary
      #   if: success()
      #   run: |
      #     echo "### ✅ Docs build successful" >> $GITHUB_STEP_SUMMARY
      #     echo "" >> $GITHUB_STEP_SUMMARY
      #     echo "**Build info:**" >> $GITHUB_STEP_SUMMARY
      #     echo "- Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
      #     echo "- Branch/Tag: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
      #     echo "- Triggered by: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
