name: Build/CLI

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      is_tag: ${{ startsWith(github.ref, 'refs/tags/') }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
          cache-dependency-path: ./pnpm-lock.yaml

      - name: pnpm-update-for-win
        if: startsWith(matrix.os, 'windows')
        run: node ./scripts/github-ci-pnpm-update.js
      
      - name: Prefetch deps
        run: pnpm fetch

      - name: Install CLI dependencies
        run: pnpm -F bililive-cli... install --frozen-lockfile --prefer-offline

      - name: build CLI
        run: pnpm -F bililive-cli... build

      - name: Move CLI package
        run: pnpm -F bililive-cli movePackage
      
      - name: Zip lib folder
        run: pnpm -F bililive-cli zip:lib

      - name: release
        if: env.is_tag == 'true'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: false
          artifacts: "packages/CLI/lib/*.zip"
          replacesArtifacts: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        if: env.is_tag == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
            packages/app/dist/*.deb
            packages/app/dist/*.snap
            packages/app/dist/*.zip
            packages/CLI/dist/*.zip
            packages/app/dist/*.exe
            packages/app/dist/*.zip
            packages/CLI/dist/*.zip
            packages/CLI/lib/*.zip

permissions:
  contents: write
